### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by joohongyoo** [facebook/SCRNNs#4]
Hello, there.

I have a question about initialization.
You know, "main.lua" has a line "torch.manualSeed(1)" at part of the initialization.
Does it work?
I thought results will not be changed because of the line.
But, I've got different results whenever I repeat it again.
Even though, most cases, the differences are not huge, sometimes they are noticeable.
Plz, give me an answer.
Thanks.

**Comment by supchop** [comment]
When using cuda, in addition to using torch.manualSeed(1), you should also use cutorch.manualSeed(1). That will make everything deterministic to an extent. I say "to an extent" because several operations on the gpu, such as Atomic Add, are inherently non-deterministic and the results could vary slightly from one run to the other. That said, adding cutorch.manualSeed(1) should surely make things more stable. I'll add that to the code in its next version.
